import { Metadata } from 'next';
import Link from 'next/link';
import { MarketingNav, Footer } from '@/components/marketing';

export const metadata: Metadata = {
  title: 'Terms of Service - AI App Builder',
  description: 'Terms of Service for AI App Builder.',
};

export default function TermsPage() {
  return (
    <>
      <MarketingNav />
      <main className="pt-24 pb-16 px-4">
        <div className="max-w-3xl mx-auto">
          {/* Header */}
          <div className="mb-12">
            <h1 className="text-4xl font-bold text-white mb-4">Terms of Service</h1>
            <p className="text-zinc-400">
              Last updated:{' '}
              {new Date().toLocaleDateString('en-US', {
                month: 'long',
                day: 'numeric',
                year: 'numeric',
              })}
            </p>
          </div>

          {/* Content */}
          <div className="prose prose-invert prose-zinc max-w-none">
            <div className="space-y-8">
              <section>
                <h2 className="text-xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
                <p className="text-zinc-400 leading-relaxed">
                  By accessing or using AI App Builder, you agree to be bound by these Terms of
                  Service. If you do not agree to these terms, please do not use our service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">2. Description of Service</h2>
                <p className="text-zinc-400 leading-relaxed">
                  AI App Builder is a software development tool that uses artificial intelligence to
                  help users create React applications. The service includes code generation, visual
                  design interpretation, and project management features.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">3. User Accounts</h2>
                <p className="text-zinc-400 leading-relaxed">
                  You must create an account to use certain features of the service. You are
                  responsible for maintaining the confidentiality of your account credentials and
                  for all activities that occur under your account.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">4. Acceptable Use</h2>
                <p className="text-zinc-400 leading-relaxed mb-4">
                  You agree not to use the service to:
                </p>
                <ul className="list-disc list-inside text-zinc-400 space-y-2">
                  <li>Generate malicious code or software</li>
                  <li>Violate any applicable laws or regulations</li>
                  <li>Infringe on intellectual property rights of others</li>
                  <li>Attempt to gain unauthorized access to our systems</li>
                  <li>Interfere with or disrupt the service</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">5. Intellectual Property</h2>
                <p className="text-zinc-400 leading-relaxed">
                  Code generated by AI App Builder is owned by you, the user. However, the AI App
                  Builder platform, including its algorithms, interface, and documentation, remains
                  our intellectual property.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">
                  6. Limitation of Liability
                </h2>
                <p className="text-zinc-400 leading-relaxed">
                  AI App Builder is provided &quot;as is&quot; without warranties of any kind. We
                  are not liable for any damages arising from your use of the service, including but
                  not limited to direct, indirect, incidental, or consequential damages.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">7. Changes to Terms</h2>
                <p className="text-zinc-400 leading-relaxed">
                  We reserve the right to modify these terms at any time. We will notify users of
                  significant changes via email or through the service interface.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">8. Contact</h2>
                <p className="text-zinc-400 leading-relaxed">
                  If you have questions about these terms, please contact us at{' '}
                  <a
                    href="mailto:legal@aiappbuilder.com"
                    className="text-blue-400 hover:text-blue-300"
                  >
                    legal@aiappbuilder.com
                  </a>
                </p>
              </section>
            </div>
          </div>

          {/* Back Link */}
          <div className="mt-12 pt-8 border-t border-zinc-800">
            <Link href="/" className="text-blue-400 hover:text-blue-300 transition-colors">
              &larr; Back to Home
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
