/**
 * Backend Architecture Specification Types
 *
 * Generated by BackendArchitectureAgent before phase generation.
 * Contains custom, app-specific backend architecture decisions.
 */

import type { FeatureDomain } from './dynamicPhases';

// ============================================================================
// CORE ARCHITECTURE SPEC
// ============================================================================

/**
 * Complete backend architecture specification for an app
 */
export interface ArchitectureSpec {
  id: string;
  appName: string;
  generatedAt: string;

  /** Claude's reasoning for architecture decisions */
  architectureReasoning: ArchitectureReasoning;

  /** Database design */
  database: DatabaseArchitecture;

  /** API design */
  api: APIArchitecture;

  /** Authentication design (if needed) */
  auth?: AuthArchitecture;

  /** Real-time architecture (if needed) */
  realtime?: RealtimeArchitecture;

  /** File storage strategy (if needed) */
  storage?: StorageArchitecture;

  /** Caching strategy (if needed) */
  caching?: CachingArchitecture;

  /** Backend phases to inject into the phase plan */
  backendPhases: BackendPhaseSpec[];

  /** Token usage for this generation */
  tokenUsage: {
    input: number;
    output: number;
    thinking?: number;
  };
}

// ============================================================================
// ARCHITECTURE REASONING
// ============================================================================

export interface ArchitectureReasoning {
  /** High-level summary of architecture decisions */
  summary: string;

  /** Why specific patterns were chosen */
  decisions: ArchitectureDecision[];

  /** Scalability considerations */
  scalabilityNotes: string[];

  /** Security considerations */
  securityNotes: string[];

  /** Performance considerations */
  performanceNotes: string[];

  /** Trade-offs acknowledged */
  tradeoffs: string[];
}

export interface ArchitectureDecision {
  area: 'database' | 'api' | 'auth' | 'realtime' | 'storage' | 'caching';
  decision: string;
  reasoning: string;
  /** The specific feature or requirement from the concept that led to this decision */
  conceptReference?: string;
  alternatives: string[];
}

// ============================================================================
// DATABASE ARCHITECTURE
// ============================================================================

export interface DatabaseArchitecture {
  /** Database strategy */
  strategy: 'sqlite' | 'postgresql' | 'supabase';

  /** Complete Prisma schema (ready to use) */
  prismaSchema: string;

  /** Table definitions with relationships */
  tables: TableDefinition[];

  /** Indexes for performance */
  indexes: IndexDefinition[];

  /** Seed data structure */
  seedData?: SeedDataSpec;

  /** Migration considerations */
  migrationNotes: string[];
}

export interface TableDefinition {
  name: string;
  description: string;
  fields: FieldDefinition[];
  relations: RelationDefinition[];
  /** Which user roles can access this table */
  accessRoles?: string[];
}

export interface FieldDefinition {
  name: string;
  type: PrismaFieldType;
  required: boolean;
  unique?: boolean;
  default?: string;
  description?: string;
}

export type PrismaFieldType =
  | 'String'
  | 'Int'
  | 'Float'
  | 'Boolean'
  | 'DateTime'
  | 'Json'
  | 'String?'
  | 'Int?'
  | 'Float?'
  | 'Boolean?'
  | 'DateTime?'
  | 'Json?'
  | 'String[]'
  | 'Int[]';

export interface RelationDefinition {
  name: string;
  type: 'one-to-one' | 'one-to-many' | 'many-to-many';
  targetTable: string;
  foreignKey?: string;
  onDelete?: 'CASCADE' | 'SET_NULL' | 'RESTRICT';
}

export interface IndexDefinition {
  name: string;
  table: string;
  fields: string[];
  unique: boolean;
  reason: string;
}

export interface SeedDataSpec {
  description: string;
  tables: {
    table: string;
    sampleData: Record<string, unknown>[];
  }[];
}

// ============================================================================
// API ARCHITECTURE
// ============================================================================

export interface APIArchitecture {
  /** API style */
  style: 'rest' | 'trpc' | 'graphql';

  /** Route structure */
  routes: APIRouteSpec[];

  /** Shared middleware */
  middleware: MiddlewareSpec[];

  /** Error handling strategy */
  errorHandling: ErrorHandlingSpec;

  /** Rate limiting configuration */
  rateLimiting?: RateLimitingSpec;
}

export interface APIRouteSpec {
  path: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  description: string;

  /** Which feature this route supports */
  feature: string;

  /** Request schema (TypeScript-like) */
  requestSchema?: string;

  /** Response schema (TypeScript-like) */
  responseSchema?: string;

  /** Auth requirements */
  requiresAuth: boolean;
  requiredRoles?: string[];

  /** Implementation notes */
  implementationNotes?: string;
}

export interface MiddlewareSpec {
  name: string;
  description: string;
  appliesTo: string[]; // Route patterns
  code: string; // Actual middleware code
}

export interface ErrorHandlingSpec {
  strategy: 'standard' | 'detailed' | 'minimal';
  customErrors: { code: string; message: string; httpStatus: number }[];
}

export interface RateLimitingSpec {
  enabled: boolean;
  defaultLimit: number;
  windowMs: number;
  routeOverrides?: { pattern: string; limit: number }[];
}

// ============================================================================
// AUTHENTICATION ARCHITECTURE
// ============================================================================

export interface AuthArchitecture {
  /** Auth strategy */
  strategy: 'next-auth' | 'supabase' | 'custom-jwt';

  /** Provider configuration */
  providers: AuthProviderSpec[];

  /** Session configuration */
  session: SessionSpec;

  /** Role-based access control */
  rbac?: RBACSpec;

  /** Auth-related files to generate */
  files: AuthFileSpec[];
}

export interface AuthProviderSpec {
  type: 'credentials' | 'oauth' | 'magic-link' | 'phone';
  provider?: string; // e.g., 'google', 'github'
  configuration: Record<string, string>;
}

export interface SessionSpec {
  strategy: 'jwt' | 'database';
  maxAge: number;
  updateAge: number;
}

export interface RBACSpec {
  roles: RoleSpec[];
  permissions: PermissionSpec[];
  rolePermissions: { role: string; permissions: string[] }[];
}

export interface RoleSpec {
  name: string;
  description: string;
  isDefault?: boolean;
}

export interface PermissionSpec {
  name: string;
  description: string;
  resource: string;
  actions: ('create' | 'read' | 'update' | 'delete')[];
}

export interface AuthFileSpec {
  path: string;
  purpose: string;
  content: string;
}

// ============================================================================
// REALTIME ARCHITECTURE
// ============================================================================

export interface RealtimeArchitecture {
  /** Realtime strategy */
  strategy: 'sse' | 'websocket' | 'polling' | 'supabase-realtime';

  /** Channels/topics */
  channels: RealtimeChannelSpec[];

  /** Implementation files */
  files: { path: string; content: string; purpose: string }[];
}

export interface RealtimeChannelSpec {
  name: string;
  description: string;
  events: { name: string; payload: string }[];
  subscribers: string[]; // Role names
}

// ============================================================================
// STORAGE ARCHITECTURE
// ============================================================================

export interface StorageArchitecture {
  /** Storage strategy */
  strategy: 'local' | 's3' | 'supabase-storage' | 'cloudinary';

  /** Buckets/folders */
  buckets: StorageBucketSpec[];

  /** File validation rules */
  validation: FileValidationSpec;

  /** Implementation files */
  files: { path: string; content: string; purpose: string }[];
}

export interface StorageBucketSpec {
  name: string;
  description: string;
  allowedMimeTypes: string[];
  maxFileSize: number; // in bytes
  isPublic: boolean;
}

export interface FileValidationSpec {
  maxSize: number;
  allowedTypes: string[];
  virusScan?: boolean;
}

// ============================================================================
// CACHING ARCHITECTURE
// ============================================================================

export interface CachingArchitecture {
  /** Caching strategy */
  strategy: 'memory' | 'redis' | 'file';

  /** Cache policies */
  policies: CachePolicySpec[];

  /** Invalidation rules */
  invalidation: InvalidationRuleSpec[];
}

export interface CachePolicySpec {
  name: string;
  pattern: string; // e.g., '/api/products/*'
  ttl: number; // seconds
  staleWhileRevalidate?: number;
}

export interface InvalidationRuleSpec {
  trigger: string; // e.g., 'POST /api/products'
  invalidates: string[]; // Cache keys to invalidate
}

// ============================================================================
// BACKEND PHASE SPECIFICATION
// ============================================================================

export interface BackendPhaseSpec {
  name: string;
  description: string;
  domain: FeatureDomain;
  priority: number; // Lower = earlier
  dependencies: string[]; // Phase names this depends on

  /** Files to generate in this phase */
  files: BackendFileSpec[];

  /** Features implemented */
  features: string[];

  /** Test criteria */
  testCriteria: string[];

  /** Estimated tokens for this phase */
  estimatedTokens: number;
}

export interface BackendFileSpec {
  path: string;
  description: string;
  /** Either provide content directly, or a generation prompt */
  content?: string;
  generationPrompt?: string;
}

// ============================================================================
// GENERATION REQUEST/RESPONSE
// ============================================================================

export interface ArchitectureGenerationOptions {
  /** Database preference (default: sqlite) */
  databasePreference?: 'sqlite' | 'postgresql' | 'supabase';

  /** Skip certain analyses */
  skipAuth?: boolean;
  skipRealtime?: boolean;
  skipStorage?: boolean;

  /** Token budget for the agent */
  maxTokenBudget?: number;

  /** Enable extended thinking */
  enableThinking?: boolean;
}

export interface ArchitectureGenerationResult {
  success: boolean;
  spec?: ArchitectureSpec;
  error?: string;
  warnings: string[];
}
