import JSZip from 'jszip';

export interface AppFile {
  path: string;
  content: string;
}

export interface ExportOptions {
  appName: string;
  files: AppFile[];
  includePackageJson?: boolean;
  includeReadme?: boolean;
  includeEnvExample?: boolean;
}

/**
 * Generate package.json for the exported app
 */
export function generatePackageJson(appName: string): string {
  const packageJson = {
    name: appName.toLowerCase().replace(/\s+/g, '-'),
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      next: '13.5.4',
      typescript: '^5',
      '@types/node': '^20',
      '@types/react': '^18',
      '@types/react-dom': '^18',
      tailwindcss: '^3.3.0',
      postcss: '^8',
      autoprefixer: '^10',
    },
    devDependencies: {
      '@types/node': '^20',
      '@types/react': '^18',
      '@types/react-dom': '^18',
      eslint: '^8',
      'eslint-config-next': '13.5.4',
      typescript: '^5',
    },
  };

  return JSON.stringify(packageJson, null, 2);
}

/**
 * Generate README.md for the exported app
 */
export function generateReadme(appName: string): string {
  return `# ${appName}

This is a Next.js application generated with AI App Builder.

## Getting Started

First, install the dependencies:

\`\`\`bash
npm install
# or
yarn install
# or
pnpm install
\`\`\`

Then, run the development server:

\`\`\`bash
npm run dev
# or
yarn dev
# or
pnpm dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Deployment

### Deploy to Vercel

The easiest way to deploy your Next.js app is to use the [Vercel Platform](https://vercel.com/new).

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=YOUR_REPO_URL)

### Deploy to Netlify

You can also deploy to Netlify:

[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start)

## Learn More

To learn more about Next.js, check out the [Next.js Documentation](https://nextjs.org/docs).

---

Generated by AI App Builder
`;
}

/**
 * Generate .env.example file
 */
export function generateEnvExample(): string {
  return `# Environment Variables
# Copy this file to .env.local and fill in your values

# Add your environment variables here
# NEXT_PUBLIC_API_URL=
# DATABASE_URL=
`;
}

/**
 * Generate next.config.js
 */
export function generateNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: ['localhost'],
  },
}

module.exports = nextConfig
`;
}

/**
 * Generate tsconfig.json
 */
export function generateTsConfig(): string {
  return `{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;
}

/**
 * Generate tailwind.config.js
 */
export function generateTailwindConfig(): string {
  return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;
}

/**
 * Generate postcss.config.js
 */
export function generatePostCssConfig(): string {
  return `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
}

/**
 * Generate .gitignore
 */
export function generateGitIgnore(): string {
  return `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`;
}

/**
 * Export app as a downloadable ZIP file
 */
export async function exportAppAsZip(options: ExportOptions): Promise<Blob> {
  const zip = new JSZip();

  // Add app files
  options.files.forEach((file) => {
    zip.file(file.path, file.content);
  });

  // Add package.json
  if (options.includePackageJson !== false) {
    zip.file('package.json', generatePackageJson(options.appName));
  }

  // Add README.md
  if (options.includeReadme !== false) {
    zip.file('README.md', generateReadme(options.appName));
  }

  // Add .env.example
  if (options.includeEnvExample !== false) {
    zip.file('.env.example', generateEnvExample());
  }

  // Add configuration files
  zip.file('next.config.js', generateNextConfig());
  zip.file('tsconfig.json', generateTsConfig());
  zip.file('tailwind.config.js', generateTailwindConfig());
  zip.file('postcss.config.js', generatePostCssConfig());
  zip.file('.gitignore', generateGitIgnore());

  // Generate the ZIP
  return await zip.generateAsync({ type: 'blob' });
}

/**
 * Download a blob as a file
 */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Parse app data to extract files
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function parseAppFiles(appData: any): AppFile[] {
  const files: AppFile[] = [];

  try {
    // Handle the app structure
    if (appData.files && Array.isArray(appData.files)) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      appData.files.forEach((file: any) => {
        files.push({
          path: file.path,
          content: file.content,
        });
      });
    }
  } catch (error) {
    console.error('Error parsing app files:', error);
  }

  return files;
}

/**
 * Generate deployment instructions for different platforms
 */
export interface DeploymentInstructions {
  platform: 'vercel' | 'netlify' | 'github';
  steps: string[];
  cliCommand?: string;
}

export function getDeploymentInstructions(
  platform: 'vercel' | 'netlify' | 'github',
  _appName: string
): DeploymentInstructions {
  switch (platform) {
    case 'vercel':
      return {
        platform: 'vercel',
        steps: [
          '1. Install Vercel CLI: npm i -g vercel',
          '2. Extract the downloaded ZIP file',
          '3. Navigate to the extracted folder',
          '4. Run: npm install',
          '5. Run: vercel',
          '6. Follow the prompts to deploy',
        ],
        cliCommand: 'vercel',
      };

    case 'netlify':
      return {
        platform: 'netlify',
        steps: [
          '1. Install Netlify CLI: npm i -g netlify-cli',
          '2. Extract the downloaded ZIP file',
          '3. Navigate to the extracted folder',
          '4. Run: npm install',
          '5. Run: npm run build',
          '6. Run: netlify deploy',
          '7. Follow the prompts to deploy',
        ],
        cliCommand: 'netlify deploy',
      };

    case 'github':
      return {
        platform: 'github',
        steps: [
          '1. Extract the downloaded ZIP file',
          '2. Navigate to the extracted folder',
          '3. Initialize git: git init',
          '4. Create a new repository on GitHub',
          '5. Add remote: git remote add origin YOUR_REPO_URL',
          '6. Commit: git add . && git commit -m "Initial commit"',
          '7. Push: git push -u origin main',
          '8. Connect to Vercel or Netlify for automatic deployments',
        ],
        cliCommand: 'git push',
      };

    default:
      return {
        platform: 'vercel',
        steps: ['Unknown platform'],
      };
  }
}
