/**
 * Image URL Injector
 *
 * Injects generated image URLs into the code produced by the AI App Builder.
 * Creates an images constants file and updates placeholder references.
 */

import type { AppImageGenerationResult } from '@/services/AppImageGenerator';

// ============================================================================
// Type Definitions
// ============================================================================

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface InjectionResult {
  files: GeneratedFile[];
  imageConstantsFile: GeneratedFile;
  imagesInjected: number;
}

// ============================================================================
// Placeholder Patterns
// ============================================================================

/**
 * Common placeholder patterns to detect and replace
 */
const PLACEHOLDER_PATTERNS = {
  // Generic placeholder URLs
  genericPlaceholder:
    /['"]https?:\/\/(?:via\.placeholder\.com|placeholder\.com|placehold\.co)[^'"]*['"]/g,

  // Unsplash placeholder patterns
  unsplashPlaceholder: /['"]https?:\/\/(?:source\.unsplash\.com|images\.unsplash\.com)[^'"]*['"]/g,

  // Lorem Picsum patterns
  loremPicsum: /['"]https?:\/\/picsum\.photos[^'"]*['"]/g,

  // Empty image src patterns
  emptySrc: /src=["']\s*["']/g,

  // Placeholder text patterns
  placeholderAlt: /alt=["'](?:placeholder|image|hero|banner)["']/gi,

  // Common variable names for hero images
  heroVariable: /(?:heroImage|heroUrl|heroBanner|bannerImage)\s*[=:]\s*['"][^'"]+['"]/g,

  // Common variable names for card images
  cardVariable: /(?:cardImage|thumbnailUrl|featureImage)\s*[=:]\s*['"][^'"]+['"]/g,
};

// ============================================================================
// Image Constants File Generator
// ============================================================================

/**
 * Generate a TypeScript constants file with all image URLs
 */
function generateImageConstantsFile(images: AppImageGenerationResult): string {
  const lines: string[] = [
    '/**',
    ' * Generated Image Assets',
    ' * ',
    ' * This file contains URLs for images generated by GPT Image 1.5 or fallback services.',
    " * These images are designed to match your app's design system.",
    images.fallbackUsed
      ? ' * Note: Fallback images were used (GPT Image was unavailable).'
      : ' * Generated using GPT Image 1.5 with your design specifications.',
    ' */',
    '',
    '// ============================================================================',
    '// Hero Image',
    '// ============================================================================',
    '',
  ];

  // Hero image
  if (images.hero) {
    lines.push(`export const HERO_IMAGE = '${images.hero.url}';`);
    lines.push(`export const HERO_IMAGE_ALT = 'Hero banner image';`);
  } else {
    lines.push(`export const HERO_IMAGE = '';`);
    lines.push(`export const HERO_IMAGE_ALT = 'Hero banner image';`);
  }

  lines.push('');
  lines.push('// ============================================================================');
  lines.push('// Card/Feature Images');
  lines.push('// ============================================================================');
  lines.push('');

  // Card images
  if (images.cards.length > 0) {
    lines.push('export const CARD_IMAGES = [');
    images.cards.forEach((card) => {
      lines.push(`  {`);
      lines.push(`    url: '${card.url}',`);
      lines.push(`    alt: '${card.title}',`);
      lines.push(`  },`);
    });
    lines.push('];');
    lines.push('');

    // Also export individual card images for easy access
    images.cards.forEach((card, index) => {
      const varName = `CARD_IMAGE_${index + 1}`;
      lines.push(`export const ${varName} = '${card.url}';`);
    });
  } else {
    lines.push('export const CARD_IMAGES: Array<{ url: string; alt: string }> = [];');
  }

  lines.push('');
  lines.push('// ============================================================================');
  lines.push('// Background Image');
  lines.push('// ============================================================================');
  lines.push('');

  // Background image
  if (images.background) {
    lines.push(`export const BACKGROUND_IMAGE = '${images.background.url}';`);
  } else {
    lines.push(`export const BACKGROUND_IMAGE = '';`);
  }

  lines.push('');
  lines.push('// ============================================================================');
  lines.push('// Helper Functions');
  lines.push('// ============================================================================');
  lines.push('');
  lines.push('/**');
  lines.push(' * Get a card image by index');
  lines.push(' */');
  lines.push('export function getCardImage(index: number): string {');
  lines.push("  return CARD_IMAGES[index]?.url || '';");
  lines.push('}');
  lines.push('');
  lines.push('/**');
  lines.push(' * Get all image URLs as an array for preloading');
  lines.push(' */');
  lines.push('export function getAllImageUrls(): string[] {');
  lines.push('  return [');
  lines.push('    HERO_IMAGE,');
  lines.push('    ...CARD_IMAGES.map(c => c.url),');
  lines.push('    BACKGROUND_IMAGE,');
  lines.push('  ].filter(Boolean);');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ============================================================================
// Code Injection Functions
// ============================================================================

/**
 * Inject image URLs into generated code files
 */
export function injectImageUrls(
  files: GeneratedFile[],
  images: AppImageGenerationResult
): InjectionResult {
  let imagesInjected = 0;
  const modifiedFiles: GeneratedFile[] = [];

  // Generate the image constants file
  const imageConstantsFile: GeneratedFile = {
    path: 'src/constants/images.ts',
    content: generateImageConstantsFile(images),
  };

  // Process each file
  for (const file of files) {
    let content = file.content;
    let fileModified = false;

    // Skip non-code files
    if (!isCodeFile(file.path)) {
      modifiedFiles.push(file);
      continue;
    }

    // Check if file contains image placeholders
    const hasPlaceholders = containsImagePlaceholders(content);

    if (hasPlaceholders) {
      // Replace hero image placeholders
      if (images.hero) {
        const heroReplaced = replaceHeroPlaceholders(content, images.hero.url);
        if (heroReplaced !== content) {
          content = heroReplaced;
          fileModified = true;
          imagesInjected++;
        }
      }

      // Replace card image placeholders
      if (images.cards.length > 0) {
        const cardsReplaced = replaceCardPlaceholders(content, images.cards);
        if (cardsReplaced !== content) {
          content = cardsReplaced;
          fileModified = true;
          imagesInjected += images.cards.length;
        }
      }

      // Add import statement if file was modified and doesn't have it
      if (
        fileModified &&
        isReactComponent(file.path) &&
        !content.includes("from '@/constants/images'")
      ) {
        content = addImageImport(content);
      }
    }

    modifiedFiles.push({
      path: file.path,
      content,
    });
  }

  return {
    files: modifiedFiles,
    imageConstantsFile,
    imagesInjected,
  };
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Check if a file is a code file that might contain image references
 */
function isCodeFile(path: string): boolean {
  return /\.(tsx?|jsx?|css|scss)$/.test(path);
}

/**
 * Check if a file is a React component
 */
function isReactComponent(path: string): boolean {
  return /\.(tsx|jsx)$/.test(path);
}

/**
 * Check if content contains image placeholders
 */
function containsImagePlaceholders(content: string): boolean {
  for (const pattern of Object.values(PLACEHOLDER_PATTERNS)) {
    if (pattern.test(content)) {
      // Reset regex lastIndex after test
      pattern.lastIndex = 0;
      return true;
    }
  }
  return false;
}

/**
 * Replace hero image placeholders with actual URL
 */
function replaceHeroPlaceholders(content: string, heroUrl: string): string {
  let result = content;

  // Replace via.placeholder.com URLs in likely hero contexts
  result = result.replace(/(['"])https?:\/\/via\.placeholder\.com\/\d+x\d+[^'"]*\1/g, (match) => {
    // Check if this is in a hero-like context
    const context = content.substring(
      Math.max(0, content.indexOf(match) - 100),
      content.indexOf(match) + match.length + 50
    );

    if (/hero|banner|header|main/i.test(context)) {
      return `'${heroUrl}'`;
    }
    return match;
  });

  // Replace heroImage variable assignments
  result = result.replace(
    /(?:heroImage|heroUrl|heroBanner|bannerImage|mainImage)\s*[=:]\s*['"][^'"]+['"]/g,
    (match) => {
      const varName = match.split(/[=:]/)[0].trim();
      return `${varName} = '${heroUrl}'`;
    }
  );

  return result;
}

/**
 * Replace card image placeholders with actual URLs
 */
function replaceCardPlaceholders(
  content: string,
  cards: Array<{ url: string; title: string }>
): string {
  let result = content;
  let cardIndex = 0;

  // Replace placeholder URLs in array contexts (likely card data)
  result = result.replace(
    /(['"])https?:\/\/(?:via\.placeholder\.com|picsum\.photos|placehold\.co)\/\d+(?:x\d+)?[^'"]*\1/g,
    () => {
      if (cardIndex < cards.length) {
        const url = cards[cardIndex].url;
        cardIndex++;
        return `'${url}'`;
      }
      return `''`;
    }
  );

  return result;
}

/**
 * Add image import to a React component file
 */
function addImageImport(content: string): string {
  const importStatement =
    "import { HERO_IMAGE, CARD_IMAGES, getCardImage } from '@/constants/images';\n";

  // Find the last import statement
  const importMatch = content.match(/^import .+;?\n/gm);

  if (importMatch && importMatch.length > 0) {
    const lastImport = importMatch[importMatch.length - 1];
    const lastImportIndex = content.lastIndexOf(lastImport) + lastImport.length;
    return content.slice(0, lastImportIndex) + importStatement + content.slice(lastImportIndex);
  }

  // No imports found, add at the top
  return importStatement + content;
}

// ============================================================================
// Standalone Utility Functions
// ============================================================================

/**
 * Create just the image constants file without modifying other files
 */
export function createImageConstantsFile(images: AppImageGenerationResult): GeneratedFile {
  return {
    path: 'src/constants/images.ts',
    content: generateImageConstantsFile(images),
  };
}

/**
 * Get import statement for the image constants
 */
export function getImageImportStatement(): string {
  return "import { HERO_IMAGE, CARD_IMAGES, getCardImage } from '@/constants/images';";
}
