import type { LayoutManifest } from '@/types/schema';

/**
 * Generate a technical specification sheet from the layout manifest
 */
export function generateSpecSheet(manifest: LayoutManifest, appName: string): string {
  const colors = manifest.designSystem?.colors || {};
  const fonts = manifest.designSystem?.fonts || { heading: 'Inter', body: 'Inter' };

  return `# Technical Design Specification: ${appName}
Generated by Gemini 3 Layout Engine

## 1. Design Tokens

### Colors
- Primary: \`${colors.primary || 'N/A'}\`
- Secondary: \`${colors.secondary || 'N/A'}\`
- Accent: \`${colors.accent || 'N/A'}\`
- Background: \`${colors.background || 'N/A'}\`
- Surface: \`${colors.surface || 'N/A'}\`
- Text: \`${colors.text || 'N/A'}\`
- Text Muted: \`${colors.textMuted || 'N/A'}\`
- Border: \`${colors.border || 'N/A'}\`

### Typography
- Heading Font: ${fonts.heading}
- Body Font: ${fonts.body}

## 2. Layout Structure
See LayoutManifest JSON for full component tree.
`;
}
